# Generated by Django 5.2.3 on 2025-07-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_price_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
