# Generated by Django 5.2.4 on 2025-07-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_searchlog_result_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='external_url',
            field=models.URLField(blank=True, help_text='Link đọc truyện online', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_year',
            field=models.PositiveIntegerField(blank=True, help_text='Năm xuất bản', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='reference_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Giá tham khảo (VNĐ)', max_digits=10, null=True),
        ),
    ]
