# Generated by Django 5.2.3 on 2025-07-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_author_bio_en_book_content_en_book_title_en'),
        ('books', '0015_book_external_url_book_publish_year_and_more'),
    ]

    operations = [
    ]
