# Generated by Django 5.2.4 on 2025-07-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_external_url_book_publish_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='info',
            field=models.TextField(blank=True, help_text='Thông tin chi tiết về tác giả'),
        ),
    ]
