# Generated by Django 5.2.4 on 2025-07-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_author_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='tieu_su',
            field=models.TextField(blank=True, help_text='Tiểu sử chi tiết'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, help_text='Tiểu sử ngắn'),
        ),
    ]
