# Generated by Django 5.2.3 on 2025-07-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_merge_20250711_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title_en',
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
