# Generated by Django 5.2.4 on 2025-07-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_remove_author_bio_en_remove_book_content_en_and_more'),
        ('books', '0018_author_birth_year_author_home_town'),
    ]

    operations = [
    ]
